### ISSUE TITLE
Google MyBusiness API

### ISSUE THREAD

**Issue by lucacorti** [googleapis/elixir-google-api#1107]
Hi, any plan to add Google MyBusiness API client?

**Comment by chrisdunelm** [comment]
This issue recently came up for C# as well: https://github.com/googleapis/google-api-dotnet-client/issues/1352

**Comment by dazuma** [comment]
There isn't a plan to add a client for MyBusiness. The reason is, MyBusiness is not a publicly accessible API—it is available only to certain partners, and is thus not part of the public API client generation process that produces the Elixir libraries.

The best I can recommend at this point is to use a normal Elixir HTTP client to make REST calls. This shouldn't be too difficult. Eventually we would like to make Elixir API client generation more self-service so it is easy to generate your own client, but it will be a while before we get to that point.

**Comment by lucacorti** [comment]
@dazuma thanks, That's the route I'm taking.
