### ISSUE TITLE
Is there a library for Ads & Ads Manager

### ISSUE THREAD

**Issue by yuchunc** [googleapis/elixir-google-api#1945]
Hi, 

I want to create a service for interacting with Google Ads and Ad Manager, is there libraries for those? 

Thank you

(for historic reasons, I think they are called adwords and dfp)

**Comment by dazuma** [comment]
The libraries provided here don't include support for Ad Manager. The Ads APIs use a different platform (SOAP-based) than most Google APIs (which are REST or gRPC based), and the mechanism used to generate these Elixir clients doesn't support the Ads platform.

We don't currently have plans to build support for the Ads platform in this repo. (It would be a lot of work because of the platform differences.) It is possible others have worked on Elixir support for Ad Manager, but I'm not aware of any such efforts.

**Comment by yuchunc** [comment]
@dazuma Looking at Ads' API, I think it is being implemented in rpc now. 

https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services

Perhaps there is some way I can help with the effort?
