### ISSUE TITLE
Using Speech to Text

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [googleapis/elixir-google-api#2124]
Hi !

I'm using the Speech to Text API.
I have made a tool to record audio from the Web user interface (48000Hz, 16bits, PCM) and send the audio via WebSocket using base64 encoding.

then I try to send to Google with (data in my websocket body):
```elixir
    encoding = "LINEAR16"
    sample_rate = 48000
    language_code = "en_US"

    request = %GoogleApi.Speech.V1.Model.LongRunningRecognizeRequest{
      audio: %GoogleApi.Speech.V1.Model.RecognitionAudio{
        content: data
      },
      config: %GoogleApi.Speech.V1.Model.RecognitionConfig{
        encoding:  encoding,
        sampleRateHertz: sample_rate,
        languageCode: language_code
      }
    }

    response = GoogleApi.Speech.V1.Api.Speech.speech_speech_recognize(
      conn,
      [body: request]
    )
```

but I get only theses messages:
```
{:ok, %GoogleApi.Speech.V1.Model.RecognizeResponse{results: nil}}
```

([this example](https://github.com/GoogleCloudPlatform/elixir-samples/blob/master/speech/lib/speech_samples.ex) don't show the streaming case ...)

Does someone has an idea to debug and have some positive results ?
Thanks,
Marc-Antoine

**Comment by MarcAntoine-Arnaud** [comment]
I have tested to record the audio sended via the WebSocket, decode the 64 and store it.
Using Node.js example I can transcribe it.

**Comment by MarcAntoine-Arnaud** [comment]
I have tried to change `speech_speech_recognize` with `speech_speech_longrunningrecognize` but nothing changes.

**Comment by fhinkel** [comment]
Hi @MarcAntoine-Arnaud, thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Cloud Platform and Elixir tags](https://stackoverflow.com/questions/tagged/google-cloud-platform+elixir) is most appropriate for general troubleshooting.
* [Google Speech to Text support](https://cloud.google.com/speech-to-text/docs/getting-support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!
