### ISSUE TITLE
Poison.EncodeError when using storage_objects_insert_iodata

### ISSUE THREAD

**Issue by lstrzebinczyk** [googleapis/elixir-google-api#3407]
Hello

I am having a problem with the `GoogleApi.Storage.V1.Api.Objects.storage_objects_insert_iodata` method. 
Please note that I am a beginner elixir usage, so if I am doing something incorrectly, I am happy to learn it.

What I am trying to do is, step by step:

1. I'm fetching a binary file from an url:

```
response = HTTPoison.get!(external_url)
```

I am expecting the response to be a mp4 file. I know this is a correct file, that plays properly.
In elixir, I can see that it's body is:

```
iex(8)> response.body
<<0, 0, 0, 32, 102, 116, 121, 112, 109, 112, 52, 50, 0, 0, 0, 0, 109, 112, 52,
  50, 109, 112, 52, 49, 105, 115, 111, 109, 97, 118, 99, 49, 0, 0, 132, 234,
  109, 111, 111, 118, 0, 0, 0, 108, 109, 118, 104, 100, 0, 0, ...>>
```

As I understand it, this is a binary type, and binary type is concidered an iodata type as well.
Therefore it should be accepted into storage_objects_insert_iodata.

However, when I am trying to actually do it, I receive:

```
iex(9)> Foo.CloudStorage.store_from_memory(response.body)                                                                                              
** (Poison.EncodeError) unable to encode value: <<132, 234, 109, 111, 111, 118, 0, 0, 0, 108, 109, 118, 104, 100, 0, 0, 0, 0, 216, 200, 142, 226, 216, 200, 142, 226, 0, 0, 2, 88, 0, 0, 131, 89, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>
    (poison) lib/poison/encoder.ex:209: Poison.Encoder.BitString.chunk_size/3
    (poison) lib/poison/encoder.ex:168: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:135: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:170: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:135: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:170: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:135: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:122: Poison.Encoder.BitString.encode/2
    (poison) lib/poison.ex:40: Poison.encode!/2
    (google_gax) lib/google_api/gax/connection.ex:182: anonymous fn/2 in GoogleApi.Gax.Connection.build_body/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (google_gax) lib/google_api/gax/connection.ex:178: GoogleApi.Gax.Connection.build_body/3
    (google_api_storage) lib/google_api/storage/v1/connection.ex:25: GoogleApi.Storage.V1.Connection.execute/2
    (google_api_storage) lib/google_api/storage/v1/api/objects.ex:561: GoogleApi.Storage.V1.Api.Objects.storage_objects_insert_iodata/7
    (foo) lib/foo/cloud_storage.ex:33: Foo.CloudStorage.store_from_memory/1
```

`store_from_memory` here does a call to storage_objects_insert_iodata plus some boilerplate. I don't think it's specific contents matter, but I'm happy 
to share if needed.

Please note, that "unable to encode" is complaining about sub-part of the binary I am passing to the method, it begins in the 2nd row, 2 chars from the end.

It fails as well when I send it this: 

```
<<0, 0, 0, 32, 102, 116, 121, 112, 109, 112, 52, 50, 0, 0, 0, 0, 109,112, 52, 50, 109, 112, 52, 49, 105, 115, 111, 109, 97, 118, 99, 49, 0, 0, 132, 234, 109, 111, 111, 118, 0, 0, 0, 108, 109, 118, 104, 100, 0>>
```

for similiarily derived substring. However I can send it different, seemingly random, binaries, and they are accepted as well.

The big picture here is: I am trying to fetch those mp4 files from an external server and reupload to google cloud. Current solution is hitting disk IO 
limits, so it's fairly slow. I was hoping to bypass disk io by sending it straight from memory.

Am I doing something wrong here, or is there an error in the lib?

**Comment by kolorahl** [comment]
I actually recall creating a workaround for this before `storage_objects_insert_iodata` was available, and I basically just copied `storage_objects_insert_simple` but changed a few lines. When I tried updating to version `0.14.0` which has the `storage_objects_insert_iodata` function, I got this same error. After comparing the two, and running a few quick tests, I believe the culprit is `add_param(:body, :data, data)`. In my own version I did `add_param(:body, :body, data)`, which works presently, **but only if I remove `add_param(:body, :metadata, metadata)`** (that function wasn't present in my own workaround since I didn't need per-object ACL definitions).

## The Problem

To understand why this is happening, we have to look at the `build_body` function in `connection.ex`. If we have body parameters `:data` and `:metadata` then we'll use line 174 (which is evident from the error trace) and we'll try to `Poison.encode!` a binary payload, which isn't a valid object for conversion to a JSON string. This makes sense: how would the Poison library know the correct way to turn the raw binary data of e.g. an audio file into a valid JSON string? It doesn't.

However, if we use `add_param(:body, :body, data)` and omit the metadata from the body, we instead use line 161, which simply puts the binary data, as-is, into the request body. This works.

## The (Maybe) Fix

I see two immediate solutions:

1. Use `Poison.encode` in the `build_body` function and check for success/error. If successful, add the resulting string and set the content type to `application/json`. If there was an error, add the data as-is and use whatever content type the API expects for raw binary data.
2. Use `add_param(:body, :body, data)` and add the Object metadata some other way that doesn't add anything additional to the body. That will ensure the request is prepared properly. I'm not sure what the effort is to add the metadata via alternate means though, so maybe this isn't feasible.

## Example of Working Code

```elixir
    request =
      Request.new()
      |> Request.method(:post)
      |> Request.url("/upload/storage/v1/b/{bucket}/o", %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1)
      })
      |> Request.add_param(:query, :name, name)
      |> Request.add_param(:body, :body, data)
      |> Request.add_optional_params(optional_params_config, optional_params)
      |> Request.library_version(@library_version)

    connection
    |> Connection.execute(request)
    |> Response.decode(opts ++ [struct: %GoogleApi.Storage.V1.Model.Object{}])
```

**Comment by enewey** [comment]
Any chance this fix gets merged in soon?
