### ISSUE TITLE
Directory API Client

### ISSUE THREAD

**Issue by vip30** [googleapis/elixir-google-api#4348]
Can we add [Directory API](https://developers.google.com/admin-sdk/directory/v1/get-start/getting-started) client in this project?

It seems other languages (Java, Node, Go...etc) also have this api client.

Here is the discovery schema
https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest

Thanks

**Comment by dazuma** [comment]
It looks like this is a case the Elixir discovery isn't handling correctly: multiple "APIs" under the same name that should live in the same library. In this case, directory, reports, and datatransfer are all "sub-apis" under admin. (Technically they're being treated as separate API versions, although they are somewhat abusing the versions concept since they aren't actually separate versions of the same API.) Elixir seems to be getting confused by this.

The right solution isn't to create a separate library (as #4350 does) with a different name like "directory" because it isn't separate from the admin API, and having "directory" be toplevel would be confusing. I think we can get it set up to treat directory and datatransfer properly as "versions" of the admin API.
